### ISSUE TITLE
Add support for ZoomControlStyle

### ISSUE THREAD

**Issue by AuthorProxy** [googlemaps/js-jest-mocks#121]
Now ZoomControlStyle is missed from this package, need to do something like this 
```
beforeAll(() => {
  initialize();
  google.maps.ZoomControlStyle = {
    DEFAULT: 0,
    SMALL: 1,
    LARGE: 2,
  };
});
```

**Comment by jpoehnelt** [comment]
This enum is deprecated. Going to close as it can be overridden as shown in your snippet.
