### ISSUE TITLE
Mocks for google.maps.Data

### ISSUE THREAD

**Issue by eegli** [googlemaps/js-jest-mocks#141]
**Is your feature request related to a problem? Please describe.**
I would like to have this library support the `google.maps.Data`, e.g. for adding GeoJSON data to a map. [Data class reference](https://developers.google.com/maps/documentation/javascript/reference/data).

 **Describe the solution you'd like**
Create mock implementation for `google.maps.Data` and provide it as a property for `google.maps.Map` as well as a standalone class from which `Data` instances can be constructed.

 **Additional context**
I'm currently mocking the [base](https://developers.google.com/maps/documentation/javascript/reference/data#Data) `Data` class manually in some project. If you are ok with this feature request, I can submit a PR with mocks for the base class. In a next step, we could also provide mocks for other classes on `google.maps.Data`, e.g. `google.maps.Data.Feature` etc.

**Comment by jpoehnelt** [comment]
A pull request would be great!

**Comment by eegli** [comment]
Done, let me know if this is ok for you. I didn't find any style guidelines so I tried to adhere to what was already there.
