### ISSUE TITLE
Docs: Bad links for issues and contributing guidelines in README

### ISSUE THREAD

**Issue by clarkedb** [googlemaps/js-jest-mocks#15]
Link issues:
1. The link to submit an issue still goes to the old repo, that this repo was preivously a part of. 
2. The link to the contributing guidelines is not defined, so it just says `[contrib]` next to the link text.

#### Steps to reproduce

  1. Look at the end of the README and try to follow either of the two aforementioned links

**Comment by clarkedb** [comment]
I have a branch with fixes for these links ready to go. I just noticed that the contributing guidelines say to submit an issue and discuss solutions first.

**Comment by jpoehnelt** [comment]
Feel free to send a pr. I recently moved this package into its own repository and missed some of those links.
