### ISSUE TITLE
Project structure and street view mocks

### ISSUE THREAD

**Issue by eegli** [googlemaps/js-jest-mocks#163]
**Describe the solution you'd like**
As this repo grows, I suggest refactoring the folder structure a little bit to facilitate development. My proposal is to implement the structure that the [v3 reference](https://developers.google.com/maps/documentation/javascript/reference) uses.
I've already created [a branch in my fork](https://github.com/eegli/js-jest-mocks/tree/feat/street-view-mocks/src) that shows how it could look like. 

Additionally, I'd like to provide mocks for the Street View Rendering and Service objects.

**Comment by jpoehnelt** [comment]
That structure looks good to me. Please submit a pull request!
