### ISSUE TITLE
Circle: add stubs for google.maps.Circle

### ISSUE THREAD

**Issue by clarkedb** [googlemaps/js-jest-mocks#17]
Is your feature request related to a problem? Please describe.
No.

Describe the solution you'd like
There should be stubs for the `google.maps.Circle` API. I'm happy to submit a PR for this.

Describe alternatives you've considered
I can mock this myself for now in my project, but it would be helpful to have the additional mock in this library so future developers don't have to do the same.

**Comment by jpoehnelt** [comment]
A pr would great!
