### ISSUE TITLE
Feature Request/Question: Implement classes as Mocks

### ISSUE THREAD

**Issue by liveFreeOrCode** [googlemaps/js-jest-mocks#175]
Hello :wave:

While using this library, I'm struggling to test the mocks embedded within the JS class objects.  For example, when the `Map` instance object isn't readily available for testing, I'm not sure the best way to go about testing if a function of the map instance was called.

What if instead of creating `Map` and everything else as a class, they are created as `jest.fn(() => {})` mock instances, so that users can retrieve them by:

```
// example test for `setCenter` to have been called
const mapMock = (global as any).google.maps.Map as jest.MockedClass<typeof google.maps.Map>;
expect(mapMock.mock.instances[0].setCenter).toHaveBeenCalled();
```

Apologies if there is a better way to do this, and I'm just not able to think of it.

**Comment by jpoehnelt** [comment]
could also modify the constructor?

```js
class _Map extends ... {
  public static: _mockInstances = [];
  constructor(...) {
    _Map._mockInstances.push(this);
  }
}
```

this would require a reset which could be added to the initialize function that users are already using

```
initialize() {
  _Map._mockInstances = [];
  (global as any).google = { ... }
...

this would be a gotcha in that it wouldn't clear if users are manually clearing mocks with jest

**Comment by liveFreeOrCode** [comment]
or this? do we need an array of instances I wonder?  We just care about the instance object of the map here, which isn't a mock that needs reset, and the mocks for the functions in the instance will be reset with `jest.resetAllMock()` or however the user wants to clear their mocks between tests

```
class _Map extends ... {
  public static: _mock;
  constructor(...) {
    _Map._mock = this;
  }
}
```
