### ISSUE TITLE
InfoWindow: Add mocks for maps.InfoWindow

### ISSUE THREAD

**Issue by samschurter** [googlemaps/js-jest-mocks#181]
**Is your feature request related to a problem? Please describe.**
No, just additional functionality

 **Describe the solution you'd like**
Mocks should exist for the maps.InfoWindow class defined here: https://developers.google.com/maps/documentation/javascript/reference/info-window#InfoWindow

 **Describe alternatives you've considered**
Currently I'm just adding the minimally required mock to the global object with the following.
```
window.google.maps.InfoWindow = jest.fn().mockImplementation(() => {
  return {
    setPosition: iwSetPositionMock,
    open: iwOpenMock,
  };
});
```

 **Additional context**
I can work on a PR if this seems like a good idea.

**Comment by jpoehnelt** [comment]
A pr would be great!
