### ISSUE TITLE
Geocoder: add stubs for maps.Geocoder

### ISSUE THREAD

**Issue by clarkedb** [googlemaps/js-jest-mocks#21]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
There should be stubs for the Geocode API. I'm happy to submit a PR for this. I'm not sure though about the optional `callback` for the `geocode` method. Should the mock be able to execute an arbitrary callback, or should it just ignore it like was done for `MVCArray.forEach`?

**Describe alternatives you've considered**
I can mock this myself for now in my project, but it would be helpful to have the additional mock in this library so future developers don't have to do the same.

**Comment by nightgrey** [comment]
+1 to this issue.

> Should the mock be able to execute an arbitrary callback, or should it just ignore it like was done for MVCArray.forEach?

Just as a notice; `Geocoder().geocode` also returns a Promise, so this should also be handled.

The types from `@types/google.maps`:
```
    geocode(
        request: google.maps.GeocoderRequest,
        callback?:
            ((a: google.maps.GeocoderResult[]|null,
              b: google.maps.GeocoderStatus) => void)|
        null): Promise<google.maps.GeocoderResponse>;
```
