### ISSUE TITLE
Best way to access constructor arguments?

### ISSUE THREAD

**Issue by samschurter** [googlemaps/js-jest-mocks#215]
I'm attempting to spy on the Marker constructor to make sure it was called with the correct options. Currently I am doing the following: 
```javascript
const markerConstructorSpy = jest.fn((...args) => {
  return new Marker(...args);
});
window.google.maps.Marker = markerConstructorSpy;
....
markerConstructorSpy.mock.calls[0][0]
```
Is this the best way? It would be convenient to be able to access a mock of the constructor directly, but currently the constructor itself is not a jest mock. 

I also tried modifying the Marker mock class with the following and it seemed to work:
```javascript
constructor(opts?: google.maps.MarkerOptions | null) {
    super();
    this._constructor(opts);
  }
  public _constructor = jest.fn();
```

Given the purpose is to see if the object was constructed properly, the constructor itself would not need to be mocked if the options were actually implemented. This would be a lot more work to implement, but it would have the benefit of being able to access the properties directly like `markerInstance1.getIcon()`, `markerInstance2.getIcon()` instead of `markerConstructorSpy.mock.calls[0][0].icon` and `markerConstructorSpy.mock.calls[1][0]`.

Is it worth adding "real" getters/setters, adding a `_constructor` mock to mirror the constructor, or just keep doing it the way I have been?

**Comment by eegli** [comment]
An alternative I see is to simply construct a new marker with no arguments and then call the `setOptions` method on the instance with your options - the effect on the new marker instance is the same. This is quite clean if you can afford to refactor your implementation.

So instead of:
```ts
const marker = new google.maps.Marker({draggable: true});
```
Something like:
```ts
const marker = new google.maps.Marker();
marker.setOptions({ draggable: true });
```

Then you can easily check if `setOptions` has been called via the `mockInstances` that is exported:

```ts
import {mockInstances, Marker} from '@googlemaps/jest-mocks';

test('Marker', () => {
  const marker = new google.maps.Marker();
  marker.setOptions({draggable: true});

  const mockMarkers = mockInstances.get(Marker);
  expect(mockMarkers[0].setOptions).toHaveBeenCalledWith({draggable: true});
});
```

**Comment by samschurter** [comment]
That's true, and it's a pretty easy solution. I'm not sure I like adding steps to the way devs have to initialize objects just for testing though. In order to depend less on the implementation details when testing I like to come at it from the perspective of "I don't care how you created the marker, as long as it's the correct marker." That's why I feel like the "best" option is to implement getters/setters and make the constructor initialize the object with the passed in options. 

I'll try your suggestion @eegli, and either use that or keep doing what I'm doing for now. If anybody IS interested in a different way to check that objects were constructed with the right options, I'm happy to start working on something.

**Comment by eegli** [comment]
@samschurter can you check the linked issue? I guess accessing a mock of the constructor is possible when the spy is setup correctly.

```ts
import {initialize, Marker} from '@googlemaps/jest-mocks';

type ConstructorArgs = ConstructorParameters<typeof Marker>;

test("Marker", () => {
  initialize();

  const markerSpy = jest
    .spyOn(google.maps, "Marker")
    .mockImplementation((...args: ConstructorArgs) => new Marker(...args));

  const marker = new google.maps.Marker({ clickable: true });
  marker.setLabel("My marker");

  // Constructor
  expect(markerSpy).toHaveBeenCalledTimes(1);
  expect(markerSpy).toHaveBeenCalledWith<ConstructorArgs>({
    clickable: true,
  });

  // Instance methods
  expect(markerSpy.mock.results[0].value.setLabel).toHaveBeenCalledWith(
    "My marker"
  );
});

```

**Comment by samschurter** [comment]
That does indeed work, thank you!
