### ISSUE TITLE
AutocompleteService: Add mocks for maps.places.AutocompleteService

### ISSUE THREAD

**Issue by samschurter** [googlemaps/js-jest-mocks#285]
**Is your feature request related to a problem? Please describe.**
No, just additional functionality

 **Describe the solution you'd like**
Mocks should exist for the maps.places.AutocompleteService class defined here:
https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service

 **Describe alternatives you've considered**
None

 **Additional context**
PR will be opened soonish

**Comment by JesusTheHun** [comment]
any update on this ?
