### ISSUE TITLE
Map.getStreetView does not return StreetViewPanorama

### ISSUE THREAD

**Issue by mvdvis-eco** [googlemaps/js-jest-mocks#324]
``The Map.getStreetView function does not return a StreetViewPanorama mock.

dist/index.js#310
```
        this.getStreetView = jest
            .fn()
            .mockImplementation(() => jest.fn());
```

This should be changed to return a StreetViewPanorama instead:
```
        this.getStreetView = jest
            .fn()
            .mockImplementation(() => new StreetViewPanorama());
```

**Comment by eegli** [comment]
Good catch. I think when the method was mocked initially, the mocked class for `StreetViewPanorama` did not exist yet, hence the wrong return value.
