### ISSUE TITLE
Trying to mock AdvancedMarkerElement

### ISSUE THREAD

**Issue by cmavromoustakos** [googlemaps/js-jest-mocks#737]
Hello

We replaced the Marker component with AdvancedMarkerElement and we have the code working but have been banging our heads against the wall trying to test the functionality.

The original test using the Marker functionality looked like this
```
      initialize()
      window.google.maps.Marker = jest.fn().mockImplementation(() => {
        return {
          addListener: addListenerSpy
        }
      })
```

Our code would add a listener and we would invoke the listener and then check to see that the proper spies were called. 

```
    describe('when user clicks on the customer marker', () => {
      it('opens info window for customer ', async () => {
        render(<Map customersWithLocation={customersWithLocation} />)

        addListenerSpy.mock.calls[0][1]()

        await waitFor(() => {
          expect(setContentinfoWindowSpy).toHaveBeenCalledTimes(1)
          expect(openInfoWindowSpy).toHaveBeenCalledTimes(1)
        })
      })
    })
```

We tried swapping out the Marker for AdvancedMarkerElement and the object is not being properly mocked, I am assuming it is because of the way the library dictates AdvancedMarkerElement be imported:

```
const { AdvancedMarkerElement } = (await google.maps.importLibrary('marker')) as google.maps.MarkerLibrary
```

Any help or direction would be greatly appreciated

**Comment by usefulthink** [comment]
Have a look at our AdvancedMarker tests here: https://github.com/visgl/react-google-maps/blob/main/src/components/__tests__/advanced-marker.test.tsx – maybe those can already give you some hints. 

Also check out the [section about testing events in the readme](https://github.com/googlemaps/js-jest-mocks?tab=readme-ov-file#testing-events).

If you are changing the implementation of the AdvancedMarkerElement class to add the spies, you also need to overwrite the return-value of the `importLibrary` function, since that would otherwise continue to return the original value. So maybe something like this will help:

```tsx
let markerLib;

beforeEach(async () => {
  class CustomAdvancedMarkerEl extends AdvancedMarkerElement { ... }

  // the element has to be registered for this override to work, but since we
  // can neither unregister nor re-register an element, a randomized name is
  // used for the element.
  customElements.define(
    `gmp-advanced-marker-${Math.random().toString(36).slice(2)}`,
    CustomAdvancedMarkerEl
  );

  markerLib = (await google.maps.importLibrary(
    'marker'
  )) as google.maps.MarkerLibrary;

  google.maps.marker.AdvancedMarkerElement = markerLib.AdvancedMarkerElement =
    AdvancedMarkerElement;
});
```

**Comment by cmavromoustakos** [comment]
Thank you for your quick reply. I will check out the docs and try your suggestion.

**Comment by cmavromoustakos** [comment]
The following worked. Pasting here for anyone else coming across this issue:

```

    describe('when user clicks on the customer marker', () => {
      it('opens info window for customer ', async () => {
        await waitFor(() => {
          render(<Map customersWithLocation={customersWithLocation} />)
        })
        const markerElements = mockInstances.get(AdvancedMarkerElement)
        const addListener = markerElements[0].addListener
        const listener = addListener.mock.lastCall[1]

        console.log('listener', listener)

        listener()

        expect(addListener).toHaveBeenCalledTimes(1);
        expect(setContentinfoWindowSpy).toHaveBeenCalledTimes(1)
        expect(openInfoWindowSpy).toHaveBeenCalledTimes(1)
      })
    })
```
